title: Mae's shit show
author: Humblehealer
email: hhumblehealerr@duck.com
description: > # this means to ignore newlines until "baseurl:"
  Just trynna survive in alaska n find some real people to do it with. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  humblehealer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
